# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dwct0UCrdGmSTvf1TJ0K3ixdUl4uXJDB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import RandomForestRegressor

df = pd.read_csv("/content/groundwater-DATASET.csv")

print("✅ Data Loaded Successfully")
print("Shape of dataset:", df.shape)

df = df.drop_duplicates().dropna()

for col in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])

print("\n📌 Cleaned Data Sample:")
print(df.head())

X = df.iloc[:, :-1] # All columns except the last one are features
y = df.iloc[:, -1]    # Last column is target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = RandomForestRegressor(random_state=42, n_estimators=100)
model.fit(X_train_scaled, y_train)

y_pred = model.predict(X_test_scaled)

rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print("\n✅ Model Performance:")
print("RMSE:", round(rmse, 3))
print("R² Score:", round(r2, 3))

importances = model.feature_importances_
features = X.columns

plt.figure(figsize=(8,5))
plt.barh(features, importances)
plt.title("🌟 Feature Importance")
plt.show()

sample_input = X_test_scaled[0].reshape(1, -1)
sample_output = model.predict(sample_input)

print("\n🔍 Sample Input (scaled):", sample_input)
print("👉 Predicted Value:", sample_output[0])
print("👉 Actual Value:", y_test.iloc[0])