import jsPDF from 'jspdf'

export function generatePDF(result) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()

  // Header bar
  doc.setFillColor(14, 165, 233)
  doc.rect(0, 0, W, 28, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(18)
  doc.setFont('helvetica', 'bold')
  doc.text('AquaVision AI', 14, 12)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Water Availability Prediction Report', 14, 20)
  doc.text(new Date().toLocaleString(), W - 14, 20, { align: 'right' })

  // Result section
  doc.setTextColor(30, 41, 59)
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('Prediction Result', 14, 42)

  const predColor =
    result.prediction === 'High'   ? [34, 197, 94]  :
    result.prediction === 'Medium' ? [245, 158, 11] :
                                     [239, 68, 68]

  doc.setFillColor(...predColor)
  doc.roundedRect(14, 47, W - 28, 22, 4, 4, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text(`${result.prediction} Water Availability`, W / 2, 61, { align: 'center' })

  // Details table
  doc.setTextColor(30, 41, 59)
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text('Details', 14, 82)

  const rows = [
    ['Confidence', result.confidence_label || `${result.confidence}%`],
    ['Current Status', result.current_status],
    ...Object.entries(result.probabilities || {}).map(([k, v]) => [`${k} Probability`, `${v.toFixed(1)}%`]),
    ...Object.entries(result.input_summary || {}).map(([k, v]) => [k.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase()), String(v)]),
  ]

  let y = 90
  doc.setFontSize(10)
  rows.forEach(([label, value], i) => {
    if (i % 2 === 0) {
      doc.setFillColor(241, 245, 249)
      doc.rect(14, y - 5, W - 28, 8, 'F')
    }
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(71, 85, 105)
    doc.text(label, 18, y)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(30, 41, 59)
    doc.text(value, W - 18, y, { align: 'right' })
    y += 10
  })

  // Footer
  doc.setFontSize(8)
  doc.setTextColor(148, 163, 184)
  doc.text('Generated by AquaVision AI – Water Availability Prediction System', W / 2, 285, { align: 'center' })

  doc.save(`aquavision-prediction-${Date.now()}.pdf`)
}
